### ISSUE TITLE
[Gogoanime] Resource not found

### ISSUE THREAD

**Issue by dausruddin** [ngomile/anigrab#7] opened 2020-09-08 03:54 UTC
**Describe the bug**
I got a a 'Resource not found' error
```
09/08 11:49:44 [ERROR] CUID#7 - Download aborted. URI=https://fvs.io/redirector?token=aFBhV0hqUFphdU44VkovNVh3Zm04MlluNnRHQXdrS21lMGhzMmFncW5CeUpybWZWdFZrUzV0WTlWU083dTNMYlBVRUVkOXh2RUlxUFpsMk9EQTRDMHViNzFISTJBWDBJUlUvaUNsOVkzampBN3E1K3NLUmZJMzFQMTBtVXN5UU9uanpIMTZBYWZYZXcwc3ZZTzRQemxJWGpCVC96Ok9qUGtDbGhWaW8xT1A5dUkwQmgxMmc9PQ
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://fvs.io/redirector?token=aFBhV0hqUFphdU44VkovNVh3Zm04MlluNnRHQXdrS21lMGhzMmFncW5CeUpybWZWdFZrUzV0WTlWU083dTNMYlBVRUVkOXh2RUlxUFpsMk9EQTRDMHViNzFISTJBWDBJUlUvaUNsOVkzampBN3E1K3NLUmZJMzFQMTBtVXN5UU9uanpIMTZBYWZYZXcwc3ZZTzRQemxJWGpCVC96Ok9qUGtDbGhWaW8xT1A5dUkwQmgxMmc9PQ
  -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
```

## Command You Entered
```
anigrab 'https://www1.gogoanime.movie/category/gekitou-crush-gear-turbo-dub'
```

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

**Comment by ngomile** [comment] 2020-09-10 00:37
Sometimes the server hosting the video file may contain the link to the file but the video no longer exists. Try using another server by changing it in the config file.

**Comment by ngomile** [comment] 2020-11-21 08:06
I tried this again and it worked just fine. I can't reproduce it but I think it's working just fine, closing.

**Closed by ngomile** 2020-11-21 08:06 UTC
